# Generated by Django 4.1.2 on 2023-06-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['title'], 'verbose_name': 'BANNERS', 'verbose_name_plural': 'BANNERS'},
        ),
        migrations.AlterModelOptions(
            name='featureditem',
            options={'verbose_name': 'FEATURED ITEMS', 'verbose_name_plural': 'FEATURED ITEMS'},
        ),
        migrations.AlterModelOptions(
            name='notificationmanager',
            options={'ordering': ['notification_title'], 'verbose_name': 'NOTIFICATION MANAGER', 'verbose_name_plural': 'NOTIFICATION MANAGER'},
        ),
        migrations.AlterModelOptions(
            name='promotions',
            options={'ordering': ['title'], 'verbose_name': 'PROMOTIONS', 'verbose_name_plural': 'PROMOTIONS'},
        ),
    ]
