# Generated by Django 4.1.2 on 2023-06-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_category_active_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'CHANNELS', 'verbose_name_plural': 'CHANNELS'},
        ),
        migrations.AlterModelOptions(
            name='itemdescription',
            options={'ordering': ['title'], 'verbose_name': 'ITEM DESCRIPTION', 'verbose_name_plural': 'ITEM DESCRIPTION'},
        ),
        migrations.AlterModelOptions(
            name='itemdescspec',
            options={'ordering': ['item_desc'], 'verbose_name': 'SPECIFICATIONS', 'verbose_name_plural': 'SPECIFICATIONS'},
        ),
        migrations.AlterModelOptions(
            name='itemlist',
            options={'ordering': ['title'], 'verbose_name': 'ITEMS', 'verbose_name_plural': 'ITEMS'},
        ),
    ]
