# Generated by Django 4.1.2 on 2023-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_category_options_alter_itemdescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescription',
            name='page_navigation',
            field=models.CharField(choices=[('models', 'models'), ('varients', 'varients'), ('details', 'details'), ('service details', 'service details'), ('used cars', 'used cars'), ('thankyou', 'thankyou')], default='models', max_length=15),
        ),
    ]
