# Generated by Django 4.1.2 on 2023-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalti', '0005_loyalti_inaugural_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltitransaction',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loyalti',
            name='business_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loyalti',
            name='inaugural_points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltientity',
            name='category',
            field=models.CharField(choices=[('Member', 'Member'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Inaugural', 'Inaugural')], default='Member', max_length=50),
        ),
    ]
