# Generated by Django 4.1.2 on 2023-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalti', '0006_loyaltitransaction_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltitransaction',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
