# Generated by Django 4.1.2 on 2023-06-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0015_alter_profile_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'verbose_name': 'PAYMENT REQUEST', 'verbose_name_plural': 'PAYMENT REQUEST'},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'PAYMENT TRANSACTION', 'verbose_name_plural': 'PAYMENT TRANSACTION'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'USER PROFILE', 'verbose_name_plural': 'USER PROFILE'},
        ),
        migrations.AlterModelOptions(
            name='profileactivity',
            options={'verbose_name': 'PROFILE ANALYTICS', 'verbose_name_plural': 'PROFILE ANALYTICS'},
        ),
        migrations.AlterModelOptions(
            name='profileaddress',
            options={'verbose_name': 'PROFILE ADDRESS', 'verbose_name_plural': 'PROFILE ADDRESS'},
        ),
        migrations.AlterModelOptions(
            name='profileaoi',
            options={'verbose_name': 'PROFILE AOI', 'verbose_name_plural': 'PROFILE AOI'},
        ),
        migrations.AlterModelOptions(
            name='profilefbtoken',
            options={'verbose_name': 'FB TOKENS', 'verbose_name_plural': 'FB TOKENS'},
        ),
        migrations.AlterModelOptions(
            name='profilenoticationpreference',
            options={'verbose_name': 'NOTIFICATION PREFERENCE', 'verbose_name_plural': 'NOTIFICATION PREFERENCE'},
        ),
        migrations.AlterModelOptions(
            name='profilesearch',
            options={'verbose_name': 'PROFILE SEARCH', 'verbose_name_plural': 'PROFILE SEARCH'},
        ),
        migrations.AlterModelOptions(
            name='profileverification',
            options={'verbose_name': 'PROFILE DOCUMENTS', 'verbose_name_plural': 'PROFILE DOCUMENTS'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'WISHLIST', 'verbose_name_plural': 'WISHLIST'},
        ),
    ]
