# Generated by Django 4.1.2 on 2023-06-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_alter_accessory_address_alter_accessory_booking_id_and_more'),
        ('profileutility', '0017_paymentrequest_cgst_sgst_paymentrequest_e_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='booking_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_transaction', to='bookings.appbooking'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Failed', 'Failed'), ('Error', 'Error')], default='Pending', max_length=50),
        ),
    ]
