# Generated by Django 4.1.2 on 2023-06-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0019_alter_paymenttransaction_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='total_amount_received',
            new_name='total_transaction_amount',
        ),
    ]
