# Generated by Django 4.1.2 on 2023-06-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilsplayground', '0005_paymentmode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'verbose_name': 'APP VERSIONS', 'verbose_name_plural': 'APP VERSIONS'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'OUTLET CITY', 'verbose_name_plural': 'OUTLET CITY'},
        ),
        migrations.AlterModelOptions(
            name='outlet',
            options={'verbose_name': 'OUTLET LOCATION', 'verbose_name_plural': 'OUTLET LOCATION'},
        ),
        migrations.AlterModelOptions(
            name='paymentmode',
            options={'verbose_name': 'PAYMENT MODE', 'verbose_name_plural': 'PAYMENT MODE'},
        ),
    ]
