# Generated by Django 4.1.2 on 2023-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_remove_loyalti_profile_delete_loyaltientity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'ACCESSORY', 'verbose_name_plural': 'ACCESSORY'},
        ),
        migrations.AlterModelOptions(
            name='appbooking',
            options={'verbose_name': 'APEX', 'verbose_name_plural': 'APEX'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'INSURANCE', 'verbose_name_plural': 'INSURANCE'},
        ),
        migrations.AlterModelOptions(
            name='newcarbooking',
            options={'verbose_name': 'NEW CAR', 'verbose_name_plural': 'NEW CAR'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'SERVICE', 'verbose_name_plural': 'SERVICE'},
        ),
        migrations.AlterModelOptions(
            name='usedcarbooking',
            options={'verbose_name': 'USED CAR - BUY', 'verbose_name_plural': 'USED CAR - BUY'},
        ),
        migrations.AlterModelOptions(
            name='usedcarsellenquiry',
            options={'verbose_name': 'USED CAR - SELL', 'verbose_name_plural': 'USED CAR - SELL'},
        ),
        migrations.AddField(
            model_name='accessory',
            name='cgst_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='e_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='i_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='net_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='special_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='appbooking',
            name='cgst_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='appbooking',
            name='e_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='appbooking',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='appbooking',
            name='i_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='appbooking',
            name='net_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='appbooking',
            name='special_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='cgst_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='e_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='i_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='net_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='special_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='newcarbooking',
            name='cgst_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='newcarbooking',
            name='e_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='newcarbooking',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='newcarbooking',
            name='i_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='newcarbooking',
            name='net_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='newcarbooking',
            name='special_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cgst_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='e_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='i_point',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='net_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='special_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
