# Generated by Django 4.1.2 on 2023-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_accessory_options_alter_appbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbooking',
            name='loyalti_transaction_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
